Repository neoforged/ModDevGradle, pull requests merged in 2024-07, with the labels that each got.

#84 Remove the dependency collector and add a global `additionalRuntimeClasspath` configuration
  src/main/java/net/neoforged/moddevgradle/dsl/RunModel.java
  src/main/java/net/neoforged/moddevgradle/internal/ModDevPlugin.java
Labels: bug, enhancement

#93 Fix double escaping of JUnit arguments
  src/main/java/net/neoforged/moddevgradle/internal/ModDevPlugin.java
Labels: bug

#103 Validate run names instead of modifying invalid ones
  src/main/java/net/neoforged/moddevgradle/dsl/InternalModelHelper.java
  src/main/java/net/neoforged/moddevgradle/dsl/RunModel.java
  src/main/java/net/neoforged/moddevgradle/internal/utils/StringUtils.java
  src/test/java/net/neoforged/moddevgradle/functional/ValidationTests.java
  testproject/build.gradle
Labels: bug

#104 Add the ability to specify Gradle tasks to be run before launching a run configuration
  README.md
  src/main/java/net/neoforged/moddevgradle/dsl/RunModel.java
  src/main/java/net/neoforged/moddevgradle/internal/ModDevPlugin.java
  src/main/java/net/neoforged/moddevgradle/internal/RunUtils.java
  src/main/java/net/neoforged/moddevgradle/internal/utils/DependencyUtils.java
Labels: enhancement

#114 Update to NFRT 1.0
  src/main/java/net/neoforged/moddevgradle/dsl/NeoFormRuntime.java
  src/main/java/net/neoforged/moddevgradle/internal/CreateMinecraftArtifactsTask.java
  src/main/java/net/neoforged/moddevgradle/internal/DownloadAssetsTask.java
  src/main/java/net/neoforged/moddevgradle/internal/ModDevPlugin.java
  src/main/java/net/neoforged/moddevgradle/internal/NeoFormRuntimeEngineTask.java
  src/main/java/net/neoforged/moddevgradle/internal/NeoFormRuntimeTask.java
Labels: enhancement, dependencies
