Repository neoforged/ModDevGradle, pull requests merged in 2024-09, with the labels that each got.

#150 Remove dependency and extendsFrom from ModModel DSL
  BREAKING_CHANGES.md
  src/main/java/net/neoforged/moddevgradle/dsl/InternalModelHelper.java
  src/main/java/net/neoforged/moddevgradle/dsl/ModModel.java
  src/main/java/net/neoforged/moddevgradle/internal/RunUtils.java
  testproject/build.gradle
  testproject/coremod/build.gradle
  testproject/coremod/src/main/resources/META-INF/MANIFEST.MF
  testproject/jijtest/build.gradle
Labels: breaking change

#159 Migrate to GradleUp shadow
  build.gradle
Labels: dependencies

#157 Add UnitTest#getLoadedMods() to configure which mods are loaded in unit tests
  README.md
  src/main/java/net/neoforged/moddevgradle/dsl/NeoForgeExtension.java
  src/main/java/net/neoforged/moddevgradle/dsl/UnitTest.java
  src/main/java/net/neoforged/moddevgradle/internal/ModDevPlugin.java
  src/main/java/net/neoforged/moddevgradle/internal/RunUtils.java
Labels: enhancement
